apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: productmicroservice
  name: productmicroservice
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: productmicroservice
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: productmicroservice
    spec:
      containers:
        - image: imalshi87z/productmicroservice:{{tag}}
          imagePullPolicy: Always
          name: productmicroservice
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          ports:
            - containerPort: 3000
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30