apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: shippingmicroservice
  name: shippingmicroservice
spec:
  ports:
  - port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    app: shippingmicroservice
status:
  loadBalancer: {}